---
title: "Import"
author: "M Schmettow"
date: "19/02/2021"
output: html_document
---

```{r setup}
library(tidyverse)
library(lubridate)
library(bayr)
library(esmerald)
```


## Summarize



## Import


```{r}
read_ethica_csv <- function(file)
{
  out <-
  read_csv(file) %>% 
    rename(Part = Name, 
           Device = `Device ID`,
           T_Scheduled = `Scheduled Time`,
           T_Issued = `Issued Time`,
           T_Response = `Response Time`,
           duration = `Duration (minutes)`) %>% 
    mutate_at(vars(starts_with("T_")), lubridate::as_datetime) %>% 
    mutate(duration = T_Response - T_Issued) %>% 
    pivot_longer(starts_with("["), names_to = "Item", values_to = "Response") %>% 
    mutate(response = as.numeric(str_match(Response, "[0-9]+"))) %>% 
    bayr::as_tbl_obs()
  class(out) <- c("tbl_esm", class(out))
  out
}

csv <- dir("inst/extdata/",full.names = T)[1:8]
read_ethica_csv(csv[2])

csv[2:6] %>% map(read_ethica_csv)

```



```{r}

print.tbl_esm <-
  function(x){
    n_Obs <- nrow(x)
    n_shown <- min(8, nrow(x))
    n_Part <- nrow(distinct(x,Part)) 
    n_Item <- nrow(distinct(x,Item))
    n_Scheduled <- nrow(distinct(x,T_Scheduled))
    cap = stringr::str_c("Table: ESM data with ", n_Obs, " observations (",
                         n_shown," shown), ",
                         n_Part, " participants and ", 
                         n_Item, " items")
    print(cap)
	  sample_n(x, 8) %>% base:::print.data.frame()
    invisible(x)
  }
```


```{r}

Data <- 
  
```



